spring:
  mail:
    host: smtp.qq.com
    port: 25
    username: 1277544516@qq.com
    password: isluoljeosikjchg
    default-encoding: UTF-8
    properties:
      timeout: 5000
      connection-timeout: 5000
      write-timeout: 5000

  redis:
    port: 6379
    password: root
